name: Run Rest Assured Tests

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name : ls
        run: ls

      - uses: JarvusInnovations/background-action@v1
        name: Start Backend Server
        with:
          run: |
            mvn spring-boot:run
          wait-on: http://localhost:8080
          tail: true
          wait-for: 5m

      - name: Testing with Rest Assured
        working-directory: ./06_PipeLine/recipe-planner-fronend-and-backend/recipe-planner-backend
        run: mvn test

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports