name: Run Rest Assured Tests

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./06_PipeLine/recipe-planner-fronend-and-backend/recipe-planner-backend
        run: mvn --batch-mode --update-snapshots verify

      - name: run spring boot backend
        working-directory: ./06_PipeLine/recipe-planner-fronend-and-backend/recipe-planner-backend
        run: mvn spring-boot:run

#      - uses: JarvusInnovations/background-action@v1
#        name: Start Backend Server
#        with:
#          run: |
#            mvn compile:compile &
#            mvn spring-boot:run
#          wait-on: http://localhost:8080
#          tail: true
#          working-directory: ./06_PipeLine/recipe-planner-fronend-and-backend/recipe-planner-backend
#
#      - name: Testing with Rest Assured
#        working-directory: ./06_PipeLine/recipe-planner-fronend-and-backend/recipe-planner-backend
#        run: mvn test
#
#      - name: Upload Surefire Reports
#        uses: actions/upload-artifact@v2
#        with:
#          name: surefire-reports
#          path: target/surefire-reports